LATEX_KONVERTIEREN: ['python3', 'python-scripte/latex_convert1.py']
LATEX_ENTFERNEN: ['python3', 'python-scripte/latexcode_entfernen2.py']
LATEX_SUCHEN_ERSETZEN: ['python3', 'python-scripte/suchen_ersetzen.py']
SYNC_TEX_FILES: ['python3', 'python-scripte/sync_tex.py']
MAKE: ['make']
MAKE_XELATEX: ['make', 'ENGINE=xelatex']
MAKE_LUALATEX: ['make', 'ENGINE=lualatex']
MAKE_CLEAN: ['make', 'clean']
MAKE_CLEAN_PDF: ['make', 'clean-pdf']
HTML_PANDOC: ['python3', 'python-scripte/html1_konverter_pandoc.py']
HTML_NAVIGATION: ['python3', 'python-scripte/html3_navigation.py']
HTML_ENTFERNEN: ['python3', 'python-scripte/html4_entfernen.py']
